In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/001_SUNNY_BHAVEEN_CHANDRA/001_My_Classes/FSDS_Feb_Batch/ALL_NOTES/June-11-Transformer

/content/drive/MyDrive/001_SUNNY_BHAVEEN_CHANDRA/001_My_Classes/FSDS_Feb_Batch/ALL_NOTES/June-11-Transformer


In [3]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  print("installing...")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

No module named 'transformers'
installing...
     |████████████████████████████████| 346 kB 14.2 MB/s 
     |████████████████████████████████| 4.2 MB 82.3 MB/s 
     |████████████████████████████████| 1.1 MB 61.2 MB/s 
     |████████████████████████████████| 212 kB 98.9 MB/s 
     |████████████████████████████████| 86 kB 6.4 MB/s 
     |████████████████████████████████| 86 kB 5.5 MB/s 
     |████████████████████████████████| 140 kB 101.9 MB/s 
     |████████████████████████████████| 596 kB 92.4 MB/s 
     |████████████████████████████████| 127 kB 103.3 MB/s 
     |████████████████████████████████| 94 kB 4.9 MB/s 
     |████████████████████████████████| 271 kB 79.2 MB/s 
     |████████████████████████████████| 144 kB 100.1 MB/s 
     |████████████████████████████████| 112 kB 97.7 MB/s 
     |████████████████████████████████| 6.6 MB 86.8 MB/s 
     |████████████████████████████████| 1.2 MB 102.0 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages 

In [4]:
model_name = "bert-base-cased"

In [5]:
from transformers import BertTokenizer, AutoTokenizer


In [6]:
tokenizer = BertTokenizer.from_pretrained(model_name)
auto_tokenizer = AutoTokenizer.from_pretrained(model_name)

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

In [15]:
example = "Transformer is an interesting library"

In [16]:
tokenizer(example)

{'input_ids': [101, 13809, 23763, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [17]:
auto_tokenizer(example)


{'input_ids': [101, 13809, 23763, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [18]:
tokenizer.save_pretrained("./sample_tokenizer")

('./sample_tokenizer/tokenizer_config.json',
 './sample_tokenizer/special_tokens_map.json',
 './sample_tokenizer/vocab.txt',
 './sample_tokenizer/added_tokens.json')

In [19]:
loaded_tokenizer = AutoTokenizer.from_pretrained("./sample_tokenizer")

In [20]:
loaded_tokenizer(example)

{'input_ids': [101, 13809, 23763, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [21]:
auto_tokenizer.tokenize(example)

['Trans', '##former', 'is', 'an', 'interesting', 'library']

In [23]:
tokens = tokenizer.tokenize(example)
tokens

['Trans', '##former', 'is', 'an', 'interesting', 'library']

In [25]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[13809, 23763, 1110, 1126, 5426, 3340]

In [26]:
tokenizer.convert_ids_to_tokens(ids)

['Trans', '##former', 'is', 'an', 'interesting', 'library']

In [27]:
updated_ids = [101, 13809, 23763, 1110, 1126, 5426, 3340, 102]

In [28]:
tokenizer.convert_ids_to_tokens(updated_ids)


['[CLS]', 'Trans', '##former', 'is', 'an', 'interesting', 'library', '[SEP]']

In [56]:
updated_ids = [101, 13809, 23763, 1110, 1126, 5426, 3340, 102, 200, 200]

In [57]:
tokenizer.convert_ids_to_tokens(updated_ids)


['[CLS]',
 'porto',
 'spores',
 'ɑ',
 'ɾ',
 'interests',
 'stars',
 '[SEP]',
 '[unused195]',
 '[unused195]']

In [59]:
updated_ids = [101, 13809, 23763, 1110, 1126, 5426, 3340, 102, 0, 0]

In [60]:
tokenizer.convert_ids_to_tokens(updated_ids)


['[CLS]',
 'porto',
 'spores',
 'ɑ',
 'ɾ',
 'interests',
 'stars',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [29]:
tokenizer.decode(updated_ids)

'[CLS] Transformer is an interesting library [SEP]'

In [30]:
tokenizer.decode(ids)

'Transformer is an interesting library'

## handling multiple sequences

In [31]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [32]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(ckpt)
model = AutoModelForSequenceClassification.from_pretrained(ckpt)

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

In [33]:
example = "I've been exploring Transformers for Natural Language Processing"

In [34]:
tokens = tokenizer.tokenize(example)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)

In [40]:
input_ids

tensor([ 1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,  6364])

In [55]:
model(input_ids)

IndexError: ignored

In [53]:
torch.unsqueeze(input_ids, dim=0)

tensor([[ 1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,  6364]])

In [54]:
model(torch.unsqueeze(input_ids, dim=0))

SequenceClassifierOutput([('logits',
                           tensor([[ 1.0319, -0.8272]], grad_fn=<AddmmBackward0>))])

In [36]:
tokenized_inputs = tokenizer(example, return_tensors='pt')

In [38]:
tokenized_inputs["input_ids"]

tensor([[  101,  1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,
          6364,   102]])

In [44]:
model(tokenized_inputs["input_ids"])

SequenceClassifierOutput([('logits',
                           tensor([[-0.3594,  0.4591]], grad_fn=<AddmmBackward0>))])

In [58]:
tokenizer.pad_token_id

0

In [65]:
example_1 = "I've been exploring Transformers for Natural Language Processing."
example_2 = "I've been exploring Transformers."


In [68]:
token_1 = tokenizer.tokenize(example_1)
print(token_1)
token_2 = tokenizer.tokenize(example_2)
print(token_2)

['i', "'", 've', 'been', 'exploring', 'transformers', 'for', 'natural', 'language', 'processing', '.']
['i', "'", 've', 'been', 'exploring', 'transformers', '.']


In [69]:
id_1 = tokenizer.convert_tokens_to_ids(token_1)
id_2 = tokenizer.convert_tokens_to_ids(token_2)

In [78]:
len(id_1)

11

In [79]:
len(id_2)

7

In [71]:
batch_id = [
            id_1,
            id_2
]
batch_id

[[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012],
 [1045, 1005, 2310, 2042, 11131, 19081, 1012]]

In [75]:
model(torch.tensor([id_1])).logits

tensor([[ 0.9019, -0.6752]], grad_fn=<AddmmBackward0>)

In [76]:
model(torch.tensor([id_2])).logits


tensor([[-0.5456,  0.7677]], grad_fn=<AddmmBackward0>)

In [77]:
model(torch.tensor(batch_id)).logits

ValueError: ignored

In [80]:
batch_id_same_seq_len = [
            id_1,
            id_1
]

In [81]:
model(torch.tensor(batch_id_same_seq_len)).logits

tensor([[ 0.9019, -0.6752],
        [ 0.9019, -0.6752]], grad_fn=<AddmmBackward0>)

In [82]:
max_len = 11

while  len(id_2)!= max_len:
  id_2.append(tokenizer.pad_token_id)

In [83]:
len(id_2)

11

In [84]:
id_2

[1045, 1005, 2310, 2042, 11131, 19081, 1012, 0, 0, 0, 0]

In [85]:
batch_id = [
            id_1,
            id_2
]
batch_id

[[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012],
 [1045, 1005, 2310, 2042, 11131, 19081, 1012, 0, 0, 0, 0]]

In [86]:
model(torch.tensor(batch_id)).logits

tensor([[ 0.9019, -0.6752],
        [ 0.7740, -0.6163]], grad_fn=<AddmmBackward0>)

In [87]:
[1]*11

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [88]:
([1]*7).extend([0,0,0,0])

In [90]:
[1]*7 + [0]*4

[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]

In [91]:
attention_mask = [
                  [1]*11,
                  [1]*7 + [0]*4
]
attention_mask

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]

In [92]:
model(
    torch.tensor(batch_id), 
    attention_mask=torch.tensor(attention_mask)
    ).logits

tensor([[ 0.9019, -0.6752],
        [-0.5456,  0.7677]], grad_fn=<AddmmBackward0>)

In [ ]:
512, 1024, truncation